{{- $items := .Values.config.items }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: casavue-cfg-items
data:
  items.yaml: |-
    {{- if $items }}
    items:
    {{- toYaml $items | nindent 4 }}
    {{- else }}
    items: []
    {{- end }}
