services:

  # main application
  # run command:
  # docker compose up
  casavue:
    image: ghcr.io/czoczo/casavue:latest
    ports:
      - "8080:8080"
    networks:
      - casavue
    volumes:
      - casavue-config:/app/config
      - casavue-dist:/app/dist

  # enables generating static HTML+JS (Vue) dashboard page
  # run command:
  # docker compose run static
  static:
    image: ghcr.io/czoczo/casavue:latest
    command: "-static"
    profiles:
      - no-auto-start
    volumes:
      - casavue-config:/app/config
      - casavue-dist:/app/dist

volumes:
  casavue-config:
  casavue-dist:

networks:
  casavue: {}